import { Link } from 'react-router-dom';
import PageShell from '../components/layout/PageShell';
import GlassCard from '../components/GlassCard';
import EmergencyBanner from '../components/EmergencyBanner';
import { CheckCircle, ShieldCheck } from '../components/icons';

const steps = [
  ['01', 'Choose the right visit', 'Browse treatments and select the concern that best fits your needs.'],
  ['02', 'Tell us what is going on', 'Answer a focused, secure health questionnaire at your own pace.'],
  ['03', 'Meet your clinician', 'A licensed physician reviews your case or meets you in a secure video visit.'],
  ['04', 'Leave with a plan', 'Get clear follow-up guidance and prescriptions when clinically appropriate.'],
];

export default function HowItWorks() {
  return <PageShell><div className="mx-auto max-w-6xl px-4 pb-20 sm:px-6"><div className="pt-2"><EmergencyBanner /></div><section className="py-16 text-center sm:py-20"><span className="section-eyebrow">A calmer way to get care</span><h1 className="mx-auto mt-5 max-w-3xl text-4xl font-extrabold tracking-[-0.045em] text-slate-deep sm:text-6xl">From question to care plan, <span className="gradient-text">simply.</span></h1><p className="section-subheading mx-auto max-w-2xl">No crowded clinic. No confusing next step. Just a clear, clinician-led care experience.</p></section><section className="grid gap-5 md:grid-cols-2">{steps.map(([number, title, description]) => <GlassCard key={number} interactive accent padding="lg" className="min-h-56"><p className="text-sm font-extrabold tracking-[0.18em] text-teal-accent">{number}</p><h2 className="mt-10 text-2xl font-bold tracking-tight text-slate-deep">{title}</h2><p className="mt-3 max-w-sm text-sm leading-relaxed text-slate-600">{description}</p></GlassCard>)}</section><section className="mt-14 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><GlassCard padding="lg" className="bg-[#e7f6fd]"><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-teal-accent">What to have ready</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.04em] text-slate-deep">A few details make your visit smoother.</h2><div className="mt-7 space-y-4">{['A private place to answer health questions honestly', 'Your preferred pharmacy, if a prescription is appropriate', 'A photo ID for secure account verification'].map((item) => <p key={item} className="flex gap-3 text-sm leading-relaxed text-slate-600"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-teal-accent" />{item}</p>)}</div></GlassCard><GlassCard padding="lg"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-accent-light text-teal-accent"><ShieldCheck className="h-6 w-6" /></div><h2 className="mt-7 text-3xl font-extrabold tracking-[-0.04em] text-slate-deep">Thoughtful care has clear boundaries.</h2><p className="mt-4 max-w-xl text-sm leading-relaxed text-slate-600">Curbside is for eligible, non-emergency concerns. Your clinician will recommend the right next step when virtual care is not appropriate.</p><Link to="/faq" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-teal-accent">Read common questions <span>→</span></Link></GlassCard></section><section className="mt-14 rounded-[2rem] bg-slate-deep px-7 py-10 text-center text-white sm:px-12"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-glow">Ready when you are</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Find the care that fits.</h2><Link to="/treatments" className="btn-primary mt-7 px-8 py-3.5">Browse treatments</Link></section></div></PageShell>;
}
