import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import PageShell from '../components/layout/PageShell';
import { intakeQuestions, isEmergencyAnswer } from '../data/intake';
import { treatments } from '../data/treatments';
import { connectIntakeToHealthie } from '../services/healthieIntake';

type Answers = Record<string, string | string[]>;

export default function Intake() {
  const [params] = useSearchParams(); const selectedCare = params.get('care');
  const [answers, setAnswers] = useState<Answers>(selectedCare ? { care: selectedCare } : {});
  const [step, setStep] = useState(0); const [complete, setComplete] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const questions = useMemo(() => intakeQuestions.filter((item) => item.id !== 'care' && (!item.showWhen || String(answers[item.showWhen.questionId] ?? '').includes(item.showWhen.includes))), [answers]);
  const question = questions[step]; const answer = answers[question?.id];
  const setAnswer = (value: string | string[]) => setAnswers((current) => ({ ...current, [question.id]: value }));
  const ready = !question.required || (Array.isArray(answer) ? answer.length > 0 : Boolean(answer));
  const submit = async () => { if (step < questions.length - 1) return setStep(step + 1); setSubmitting(true); try { await connectIntakeToHealthie({ firstName: String(answers.firstName), lastName: String(answers.lastName), email: String(answers.email), answers }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to connect account.'); setComplete(true); } finally { setSubmitting(false); } };
  if (!selectedCare) return <PageShell><div className="mx-auto max-w-6xl px-4 pb-20 sm:px-6"><section className="py-12 sm:py-20"><span className="section-eyebrow">Private care intake</span><h1 className="mt-5 max-w-3xl text-4xl font-extrabold tracking-[-.055em] text-slate-deep sm:text-6xl">What can we help you with?</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-slate-600">Choose a care option to begin a focused set of questions.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{treatments.map((t) => <Link key={t.id} to={`/intake?care=${encodeURIComponent(t.name)}`} className="intake-care-option"><span className="text-xs font-bold uppercase tracking-[.14em] text-teal-accent">{t.mode === 'video' ? 'Video visit' : 'Async care'}</span><h2>{t.name}</h2><p>{t.description}</p><span className="mt-5 inline-block text-sm font-bold text-teal-accent">Start questions →</span></Link>)}</div></section></div></PageShell>;
  if (complete) return <PageShell><div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24"><section className="intake-complete rounded-[2rem] p-7 sm:p-12"><span className="intake-check">✓</span><p className="mt-6 text-sm font-bold uppercase tracking-[.15em] text-teal-accent">{error ? 'Connection needs attention' : 'Intake received'}</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.055em] text-slate-deep sm:text-5xl">{error ? 'We could not connect your Healthie account yet.' : 'Check your email to activate your portal.'}</h1><p className="mt-5 leading-relaxed text-slate-600">{error ? error : 'We sent a secure Healthie invitation to your email address. Open the link, create your password, and Healthie will take you into your patient portal.'}</p><Link to="/" className="mt-7 inline-block text-sm font-bold text-teal-accent">Return home</Link></section></div></PageShell>;
  if (isEmergencyAnswer(answers['red-flags'])) return <PageShell><div className="mx-auto max-w-3xl px-4"><section className="mt-12 rounded-3xl border border-red-200 bg-red-50 p-7"><h1 className="font-extrabold text-red-950">Please seek emergency care now.</h1><p className="mt-3 text-red-900">Call 911 or go to the nearest emergency department.</p></section></div></PageShell>;
  return <PageShell><div className="mx-auto max-w-3xl px-4 pb-20 sm:px-6"><section className="pt-10 sm:pt-16"><Link to="/intake" className="text-sm font-bold text-teal-accent">← Back to care options</Link><div className="mt-7 flex justify-between gap-5"><div><span className="section-eyebrow">Private care intake</span><h1 className="mt-4 text-4xl font-extrabold tracking-[-.055em] text-slate-deep sm:text-5xl">A few questions to guide your care.</h1></div><span className="pt-2 text-sm font-bold text-slate-500">{step + 1} of {questions.length}</span></div><div className="mt-8 h-2 overflow-hidden rounded-full bg-[#d9edf5]"><div className="h-full rounded-full bg-teal-accent" style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div></section><section className="intake-card mt-10 rounded-[2rem] p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-accent">{question.section}</p><h2 className="mt-4 text-2xl font-extrabold tracking-[-.04em] text-slate-deep sm:text-3xl">{question.prompt}</h2>{question.helpText && <p className="mt-3 text-sm text-slate-600">{question.helpText}</p>}<div className="mt-8">{question.type === 'text' ? <textarea className="form-input min-h-32 resize-y" value={String(answer ?? '')} onChange={(e) => setAnswer(e.target.value)} /> : question.type === 'number' || question.type === 'date' ? <input className="form-input max-w-xs" type={question.type} value={String(answer ?? '')} onChange={(e) => setAnswer(e.target.value)} /> : <div className="grid gap-3">{question.options?.map((option) => { const selected = question.type === 'multi' ? Array.isArray(answer) && answer.includes(option) : answer === option; const value = question.type === 'multi' ? (selected ? (answer as string[]).filter((x) => x !== option) : [...(Array.isArray(answer) ? answer : []), option]) : option; return <button type="button" key={option} onClick={() => setAnswer(value)} className={`intake-option text-left ${selected ? 'intake-option--selected' : ''}`}><span className="intake-radio">{selected && '✓'}</span>{option}</button>; })}</div>}</div><div className="mt-10 flex justify-between gap-3"><button type="button" className="btn-secondary" disabled={step === 0 || submitting} onClick={() => setStep(step - 1)}>Back</button><button type="button" className="btn-primary" disabled={!ready || submitting} onClick={submit}>{submitting ? 'Connecting securely…' : step === questions.length - 1 ? 'Submit and continue securely' : 'Continue'} →</button></div></section></div></PageShell>;
}
