import { Link } from 'react-router-dom';
import PageShell from '../components/layout/PageShell';
import EmergencyBanner from '../components/EmergencyBanner';
import TreatmentCard from '../components/TreatmentCard';
import GlassCard from '../components/GlassCard';
import { AsyncIcon, VideoIcon } from '../components/icons';
import { treatments } from '../data/treatments';

export default function Treatments() {
  return <PageShell><div className="mx-auto max-w-6xl px-4 pb-20 sm:px-6"><div className="pt-2"><EmergencyBanner /></div><section className="py-16 sm:py-20"><span className="section-eyebrow">Care for everyday health</span><h1 className="mt-5 max-w-3xl text-4xl font-extrabold tracking-[-0.045em] text-slate-deep sm:text-6xl">Choose a treatment. <span className="gradient-text">Start feeling better.</span></h1><p className="section-subheading max-w-2xl">Select a concern to begin a private consultation with a licensed clinician.</p><div className="mt-10 grid gap-5 md:grid-cols-2"><GlassCard padding="md" className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-teal-accent-light text-teal-accent"><AsyncIcon className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-deep">Async visits</h2><p className="mt-1 text-sm leading-relaxed text-slate-600">Complete your visit on your schedule. A clinician reviews your information and shares the appropriate next step.</p></div></GlassCard><GlassCard padding="md" className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-sky-100 text-sky-700"><VideoIcon className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-deep">Video visits</h2><p className="mt-1 text-sm leading-relaxed text-slate-600">Choose a live visit when a conversation or visual evaluation can make care more helpful.</p></div></GlassCard></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{treatments.map((treatment) => <TreatmentCard key={treatment.id} treatment={treatment} />)}</div></section><section className="grid gap-6 rounded-[2rem] bg-[#e7f5fb] px-7 py-10 sm:px-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="section-eyebrow">Not sure where to start?</span><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.045em] text-slate-deep">We can help you understand the care experience.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-600">Review how Curbside works before choosing a treatment. For urgent or emergency symptoms, seek immediate in-person care.</p></div><Link to="/how-it-works" className="btn-primary w-fit whitespace-nowrap">How it works <span className="ml-1">→</span></Link></section></div></PageShell>;
}
